version: "3.9"

services:

  devops-control-center:

    build:
      context: ./Backend

    container_name: devops-control-center

    ports:
      - "5000:5000"

    restart: unless-stopped

    volumes:
      - ./Backend:/app

    environment:
      FLASK_ENV: development