version: "3.9"

services:

  devops-control-center:

    build:
      context: ./Backend

    container_name: devops-control-center

    ports:
      - "5000:5000"

    env_file:
      - ./Backend/.env

    volumes:
      - ./Backend:/app

    restart: unless-stopped